### ISSUE TITLE
new chunk type for listing preferred scaling algorithms.

### ISSUE THREAD

**Issue by lolbinarycat** [w3c/PNG-spec#455] opened 2024-06-27 09:07 UTC
something like an sALG chunk that contains a comma-seperated list of scaling algorithms, from most to least preferred.  "nn" stands for "nearest neighbor".  software is free to ignore the field if it does not support any of the listed algorithms.

this allows pixel artists to upload their art at original quality without it becoming a blurry mess.

**Comment by Crissov** [comment] 2024-06-27 09:24
Is this a duplicate of #21?

**Comment by ProgramMax** [comment] 2024-06-27 13:10
It is. However, @lolbinarycat's suggestion to make it an enum rather than a bool is a good idea. I'll close this as a duplicate and call out the enum benefit over there.

**Closed by ProgramMax** 2024-06-27 13:10 UTC
Labels: duplicate
